@startuml
!theme plain
title RDCU pour redemarrerJeu

participant ":JeuDeDes" as jeu
participant "joueurs:\nMap<String, Joueur>" as joueurs

-> jeu : redemarrerJeu()
activate jeu
note right of jeu : selon Contrôleur\n(JeuDeDés est\nl'objet racine)

jeu -> joueurs : clear()
activate joueurs
note right of joueurs : selon Expert
deactivate joueurs

deactivate jeu

@enduml