name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: build
      run: npm run build --if-present
    - name: run test
      run: npm run test
    - name: actions/upload-artifact@v2
      run: echo hello > world.txt
      uses: actions/upload-artifact@v2
      with: 
        name: my-artifact
        path: world.txt
    env:
        CI: true