name: Node.js CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

    steps:
    
      - uses: actions/checkout@v2
      - run: echo ::set-env name=FILENAME::"ReadMeSquelette.md" 
   
      - name: Check file ReadMeSquelette
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "ReadMeSquelette.md" 

        
      - run: echo "SUCCESS => $FILENAME exits" >> report_correction.txt
        if: steps.check_files.outputs.files_exists == 'true'
      - run: echo "ERROR => $FILENAME do not exits" >> report_correction.txt
        if: steps.check_files.outputs.files_exists == 'false'
        
      - run: echo ::set-env name=TEXT_TO_VERIFY::"Le Joueur demande à démarrer le jeu en s" 
      - run: echo ::set-env name=NB_LINES::$(grep -F "$TEXT_TO_VERIFY"  $FILENAME | wc -l)
      - run: echo "SUCCESS => $TEXT_TO_VERIFY" >> report_correction.txt
        if: env.NB_LINES == '1'
      - run: echo "ERRPR => $TEXT_TO_VERIFY" >> report_correction.txt
        if: env.NB_LINES == '0'
       

      - run: echo "XXXXXXXXXX"
      - uses: yvanross/github-actions@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo $NB_TEST
      - run: cat report_correction.txt

      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat

      - name: environement variable
        run:  echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
   
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build --if-present
      - name: run test
        run: npm run test
      - name: actions/upload-artifact@v2
        run: echo hello > world.txt
      - name: upload word.txt
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: world.txt
      - name: Verify presence of Le Joueur demande à redémarrer l'application.




    env:
        CI: true